# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# クラス、モジュールをcompact形式で記述
ClassAndModuleChildren:
  EnforcedStyle: compact

# ABCサイズをMAX20に緩和
Metrics/AbcSize:
  Enabled: true
  Max: 30
