angular.module(
  'newAccountBook', ['ngAnimate',
                     'ngCookies',
                     'ngTouch',
                     'ngSanitize',
                     'ngMessages',
                     'ngAria',
                     'ngResource',
                     'ngTagsInput',
                     'angulartics', 'angulartics.google.analytics',
                     'color.picker',
                     'angulike',
                     'mp.autoFocus',
                     'ui.router',
                     'ui.bootstrap',
                     'ui.sortable',
                     'pascalprecht.translate',
                     'LocalStorageModule',
                     'angular-flexslider',
                     'hc.marked',
                     'toastr']
)
