default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: account-book-pig_development

test:
  <<: *default
  database: account-book-pig_test

production:
  <<: *default
  database: account-book-pig_production
  username: account-book-pig
  password: <%= ENV['ACCOUNT-BOOK-PIG_DATABASE_PASSWORD'] %>
