default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: account-book-pig_development

test:
  <<: *default
  database: account-book-pig_test

production:
  <<: *default
  database: account-book-pig_production
